version: '3.8'

services:
  app:
    build: .
    container_name: tibet_app
    ports:
      - "8080:8080"
    environment:
      DB_URL_: ${DB_URL}
      DB_USERNAME_: ${DB_USERNAME}
      DB_PASSWORD_: ${DB_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
      
  database:
    image: postgres:14
    container_name: database_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $DB_NAME"]
      interval: 3s
      timeout: 1s
      retries: 3